# this is a convenience Dockerfile which enables macOS users
# to build msitools in an isolated environment
# corresponds to .gitlab-ci.yml
FROM fedora:30

RUN rm -f /etc/rpm/macros.image-language-conf

RUN echo 'zchunk=False' >>/etc/dnf/dnf.conf

RUN dnf update -y --nogpgcheck

RUN dnf install -y --nogpgcheck dnf-plugin-builddep intltool \
        glib2-devel gobject-introspection-devel \
        libuuid-devel vala libgsf-devel \
        libgcab1-devel git libtool make \
        redhat-rpm-config \
        bison bison-devel bison-runtime \
        perl-XML-XPath \
        mingw32-adwaita-icon-theme \
        mingw64-adwaita-icon-theme \
        mingw32-atk \
        mingw64-atk \
        mingw32-bzip2 \
        mingw64-bzip2 \
        mingw32-cairo \
        mingw64-cairo \
        mingw32-celt051 \
        mingw64-celt051 \
        mingw32-curl \
        mingw64-curl \
        mingw32-dlfcn \
        mingw64-dlfcn \
        mingw32-expat \
        mingw64-expat \
        mingw32-fontconfig \
        mingw64-fontconfig \
        mingw32-freetype \
        mingw64-freetype \
        mingw32-gcc-c++ \
        mingw64-gcc-c++ \
        mingw32-gcc \
        mingw64-gcc \
        mingw32-gdk-pixbuf \
        mingw64-gdk-pixbuf \
        mingw32-gettext \
        mingw64-gettext \
        mingw32-glib2 \
        mingw64-glib2 \
        mingw32-glib-networking \
        mingw64-glib-networking \
        mingw32-gmp \
        mingw64-gmp \
        mingw32-gnutls \
        mingw64-gnutls \
        mingw32-gsm \
        mingw64-gsm \
        mingw32-gstreamer1-plugins-bad-free \
        mingw64-gstreamer1-plugins-bad-free \
        mingw32-gstreamer1-plugins-base \
        mingw64-gstreamer1-plugins-base \
        mingw32-gstreamer1-plugins-good \
        mingw64-gstreamer1-plugins-good \
        mingw32-gstreamer1 \
        mingw64-gstreamer1 \
        mingw32-gstreamer-plugins-bad-free \
        mingw64-gstreamer-plugins-bad-free \
        mingw32-gstreamer-plugins-base \
        mingw64-gstreamer-plugins-base \
        mingw32-gstreamer-plugins-good \
        mingw64-gstreamer-plugins-good \
        mingw32-gstreamer \
        mingw64-gstreamer \
        mingw32-gtk2 \
        mingw64-gtk2 \
        mingw32-gtk3 \
        mingw64-gtk3 \
        mingw32-gtk-vnc2 \
        mingw64-gtk-vnc2 \
        mingw32-gtk-vnc \
        mingw64-gtk-vnc \
        mingw32-gvnc \
        mingw64-gvnc \
        mingw32-harfbuzz \
        mingw64-harfbuzz \
        mingw32-hicolor-icon-theme \
        mingw64-hicolor-icon-theme \
        mingw32-icu \
        mingw64-icu \
        mingw32-ilmbase \
        mingw64-ilmbase \
        mingw32-jasper \
        mingw64-jasper \
        mingw32-json-glib \
        mingw64-json-glib \
        mingw32-libepoxy \
        mingw64-libepoxy \
        mingw32-libffi \
        mingw64-libffi \
        mingw32-libgcrypt \
        mingw64-libgcrypt \
        mingw32-libgovirt \
        mingw64-libgovirt \
        mingw32-libgpg-error \
        mingw64-libgpg-error \
        mingw32-libidn2 \
        mingw64-libidn2 \
        mingw32-libjpeg-turbo \
        mingw64-libjpeg-turbo \
        mingw32-libogg \
        mingw64-libogg \
        mingw32-libpng \
        mingw64-libpng \
        mingw32-libsoup \
        mingw64-libsoup \
        mingw32-libssh2 \
        mingw64-libssh2 \
        mingw32-libtasn1 \
        mingw64-libtasn1 \
        mingw32-libtheora \
        mingw64-libtheora \
        mingw32-libtiff \
        mingw64-libtiff \
        mingw32-libusbx \
        mingw64-libusbx \
        mingw32-libvirt-glib \
        mingw64-libvirt-glib \
        mingw32-libvirt \
        mingw64-libvirt \
        mingw32-libvorbis \
        mingw64-libvorbis \
        mingw32-libxml2 \
        mingw64-libxml2 \
        mingw32-nettle \
        mingw64-nettle \
        mingw32-nspr \
        mingw64-nspr \
        mingw32-OpenEXR \
        mingw64-OpenEXR \
        mingw32-openssl \
        mingw64-openssl \
        mingw32-opus \
        mingw64-opus \
        mingw32-orc \
        mingw64-orc \
        mingw32-p11-kit \
        mingw64-p11-kit \
        mingw32-pango \
        mingw64-pango \
        mingw32-pcre \
        mingw64-pcre \
        mingw32-pixman \
        mingw64-pixman \
        mingw32-portablexdr \
        mingw64-portablexdr \
        mingw32-readline \
        mingw64-readline \
        mingw32-rest \
        mingw64-rest \
        mingw32-SDL \
        mingw64-SDL \
        mingw32-speex \
        mingw64-speex \
        mingw32-spice-glib \
        mingw64-spice-glib \
        mingw32-spice-gtk3 \
        mingw64-spice-gtk3 \
        mingw32-sqlite \
        mingw64-sqlite \
        mingw32-termcap \
        mingw64-termcap \
        mingw32-usbredir \
        mingw64-usbredir \
        mingw32-wavpack \
        mingw64-wavpack \
        mingw32-win-iconv \
        mingw64-win-iconv \
        mingw32-winpthreads \
        mingw64-winpthreads \
        mingw32-zlib \
        mingw64-zlib \
